# Available Variables:
# <NAME> Player's name
# <WORLD> World name
# <X> X coordinate
# <Y> Y Coordinate
# <Z> Z coordinate
# <N> Switches to next line
# <PLAYERS> Number of players online
# <MAXPLAYERS> Max amount of players
# <PING> Player's ping
# <TPS> Server TPS
# <FNAME> Faction name
# <MONEY> Money amount from EconomyAPI

Message: "§d§o§lA§bR§6K§aI§f COIN*§eНик§f:§d <NAME>*§l§o§aБаланс§f: <MONEY>§a $ *§bОнлайн§7:§f <PLAYERS>*§eПинг§7:§f <PING>"
